"""Added account table

Revision ID: 83269017be69
Revises: 5e05114ef8c1
Create Date: 2023-08-30 17:49:11.958861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83269017be69'
down_revision: Union[str, None] = '5e05114ef8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'address1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'address2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_address_id'), 'address', ['id'], unique=False)
    op.add_column('todos', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_owner_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'])
    op.drop_column('todos', 'owner')
    op.drop_constraint('address_users_fk', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('address_users_fk', 'users', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.add_column('todos', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_owner_fkey', 'todos', 'users', ['owner'], ['id'])
    op.drop_column('todos', 'owner_id')
    op.drop_index(op.f('ix_address_id'), table_name='address')
    op.alter_column('address', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'address2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'address1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
